services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hashhash
      POSTGRES_DB: db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hashhash
      POSTGRES_DB: db
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth-db-data:
  inventory-db-data: