services:
  auth-service:
    build:
      context: ../auth-service
    container_name: auth-service
    env_file:
      - ../auth-service/.env
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "50051:50051"
    restart: unless-stopped

  inventory-service:
    build:
      context: ../inventory-service
    container_name: inventory-service
    env_file:
      - ../inventory-service/.env
    depends_on:
      inventory-db:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "50052:50052"
    restart: unless-stopped

  stock-service:
    build:
      context: ../stock-service
    container_name: stock-service

    env_file:
      - ../stock-service/.env
    networks:
      - mynetwork
    restart: unless-stopped

  api-gateway:
    build:
      context: ../api-gateway
    container_name: api-gateway
    env_file:
      - ../api-gateway/.env
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge